// <auto-generated />
using System;
using BicycleStation.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BicycleStation.Migrations
{
    [DbContext(typeof(BicycleStationDbContext))]
    [Migration("20230727161418_AddBicyclePumpTable")]
    partial class AddBicyclePumpTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("BicycleStation.Model.BicyclePump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RepairStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepairStationId");

                    b.ToTable("BicyclePump");
                });

            modelBuilder.Entity("BicycleStation.Model.RepairStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coordinates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTools")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitorCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RepairStations");
                });

            modelBuilder.Entity("BicycleStation.Model.BicyclePump", b =>
                {
                    b.HasOne("BicycleStation.Model.RepairStation", "RepairStation")
                        .WithMany("BicyclePumps")
                        .HasForeignKey("RepairStationId");

                    b.Navigation("RepairStation");
                });

            modelBuilder.Entity("BicycleStation.Model.RepairStation", b =>
                {
                    b.Navigation("BicyclePumps");
                });
#pragma warning restore 612, 618
        }
    }
}
