// <auto-generated />
using BicycleStation.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BicycleStation.Migrations
{
    [DbContext(typeof(BicycleStationDbContext))]
    partial class BicycleStationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("BicycleStation.Model.RepairStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coordinates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPump")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTools")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitorCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RepairStations");
                });
#pragma warning restore 612, 618
        }
    }
}
